### ISSUE TITLE
categoryUrl is not defined

### ISSUE THREAD

**Issue by kumavis** [pdehaan/alexa-top-sites#3]
`ReferenceError: categoryUrl is not defined`

**Comment by pdehaan** [comment]
Looks like Alexa updated their HTML, which breaks this sub-sub-par tool.
Sorry, I don't use this tool anymore. 🤷‍♀️ 

Published [v2.0.0](https://www.npmjs.com/package/alexa-top-sites) to npm.

**Comment by kumavis** [comment]
fwiw the original issue was not resolved, this var is not defined
https://github.com/pdehaan/alexa-top-sites/blob/master/index.js#L35

**Comment by pdehaan** [comment]
Lame. Published v2.0.1.

I swear I fixed that earlier, but then I guess agressively Ctrl+Zed it back out when trying to test Alexa CSS selectors.

**Comment by pdehaan** [comment]
Let me know if you want take ownership of this module. I'd be more than happy to transfer the GitHub repo and npm module over. Clearly I haven't touched it in 11+ months and probably won't again until Alexa changes their HTML markup.
